## Matrix properties
### example Matrix

\begin{equation}
\underbrace{\begin{pmatrix} 1 & 2 & 4 \\ 1 & 1 & 2 \\ 1 & 1 & 2 \\ \end{pmatrix}}_{\text{matrix A 3x3}} \underbrace{\begin{pmatrix} x \\ y \\ z \\ \end{pmatrix}}_{\text{ vector 3x1}} = \underbrace{\begin{pmatrix} x' \\ y' \\ z' \\ \end{pmatrix}}_{\text{image 3x1}} = \underbrace{\begin{pmatrix} 1x+2y+4z \\ 1x+1y+2z \\ 1x+1y+2z \\ \end{pmatrix}}_{\text{image 3x1}} = x \underbrace{\begin{pmatrix} 1 \\ 1 \\ 1 \\ \end{pmatrix} + y \underbrace{\begin{pmatrix} 2 \\ 1 \\ 1 \\ \end{pmatrix} + z \begin{pmatrix} 4 \\ 2 \\ 2 \\ \end{pmatrix}}_{\text{linear dependent!}}}_{\text{columnspace}}
\end{equation}


### calculating nullspace

\begin{equation}
\underbrace{\begin{pmatrix} 1 & 2 & 4 \\ 1 & 1 & 2 \\ 1 & 1 & 2 \\ \end{pmatrix}}_{\text{Matrix A 3x3}} \underbrace{\begin{pmatrix} x \\ y \\ z \\ \end{pmatrix}}_{\text{ Vektor 3x1}} = \underbrace{\begin{pmatrix} 0 \\ 0 \\ 0 \\ \end{pmatrix}}_{\text{zero vector}} \\
\Leftrightarrow
\underbrace{\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 2 \\ 0 & 0 & 0 \\ \end{pmatrix}}_{\text{Matrix A 3x3}} \underbrace{\begin{pmatrix} x \\ y \\ z \\ \end{pmatrix}}_{\text{ Vektor 3x1}} = \underbrace{\begin{pmatrix} 0 \\ 0 \\ 0 \\ \end{pmatrix}}_{\text{zero vector}} \\
\Rightarrow x=0 \quad \text{and} \quad y=2z \\
\Rightarrow nul(A) = \alpha \begin{pmatrix} 0 \\ 2 \\ 1 \\ \end{pmatrix}
\end{equation}

### matrix properties

<b>kernel (ker) / nullspace (nul):</b><br>
set of all vectors wich get maped to the zero vector by the transformation A. <br>

<b>corank / defekt :</b><br>
corank(A) = dim( ker(A) ) <br>

<b>image (im):</b><br>
set of all vectors wich get maped to non-zero vectors by the transformation. Equal to columnspace (and rowspace) of the matrix (after removing linear dependent entries). <br>

<b>rank (rank):</b><br>
rank(A) = dim( im(A) ) <br>


### rank-nullity theorem (Rangsatz)
\begin{equation}
dim(A) = \underbrace{dim(ker(A))}_{corank(A)} + \underbrace{dim(im(A))}_{rank(A)}
\end{equation}

## unitary transformation
A unitary transform preserves length:<br>
$<x,y> = <Ux,Uy> = <x,U^H Uy>$ <br>
From this follows, that the conjugate transpose is equal to the inverse:<br>
$U U^H = U^H U = \mathbb{1}$ ; $U^+=U^H$ <br>

### eigenvalues and eigenvectors

Eigenvectors are vectors, wich only change length by multiplication with A but keep they previous direction.<br> The corresponding eigenvalues are the scale-factors, by wich the vectors change lenght.

\begin{equation}
Ax = \lambda x \\
\Leftrightarrow Ax = \mathbb{1} \lambda x \\
\Leftrightarrow (A-\mathbb{1} \lambda)x=0 \\
\Rightarrow det(A-\lambda) = 0
\end{equation}

=> $\lambda_{1,2,...}$ (Eigenvalues)

\begin{equation}
(A-\mathbb{1} \lambda)x=0
\end{equation}

=> $x_{1,2,...}$ (Eigenvectors)


### solution to linear system of equations

A solution to the system of linear equations $Ax=b$ is given by $x=A^{-1}b$, where $A^{-1}$ can be computed by manipulation of matrix A:

\begin{equation}
Ax = \mathbb{1} b \qquad \Leftrightarrow \qquad \mathbb{1} x = A^{-1} b
\end{equation}

or with the adjugate and determinant of A:

\begin{equation}
A^{-1} = \frac{adj(A)}{det(A)} \\
\end{equation}

with the adjugate equal to the adjungate transpose of the cofactor matrix $adj(A)=cof(A)^H$ , where every element of the cofactor matrix $c_{i,j}=cof(A)$ at position i,j is caclulated by the minor (sub-determinant) of A at this position $M_{i,j}$ times $(-1)^{i+j}$.<br><br>
The solution only exist, if b is in the columspace of A ($b \in im(A)$).


## Singular value decomposition SVD
A Matrix X can be decomposed into two unitary matrices U and V and a diagonal matrix $\Sigma$.

\begin{equation}
X = U \Sigma V^H \\
\Leftrightarrow X^H = V \Sigma U^H
\end{equation}

<b>motivation</b><br>
The matrix X of size n x m can be composed of m columnvectors $x_i$, wich represent one data instance (<b>sample</b>). One sample has multiple <b>parameters</b> e.g. size, weight and height of one signle person or all pixel values from one picture of a persons face. Usually there are more data parameters than data samples (n>>m).

\begin{equation}
\underbrace{\begin{pmatrix} | & ... & | \\ x_1 & ... & x_m \\ | & ... & | \\ \end{pmatrix}}_{n x m} = \underbrace{\begin{pmatrix} | & ... & | \\ u_1 & ... & u_n \\ | & ... & | \\ \end{pmatrix}}_{n x n} \underbrace{\begin{pmatrix} \sigma_1 & 0 & 0 \\ 0 & ... & 0 \\ 0 & 0 & \sigma_m \\ 0 & 0 & 0 \\ \end{pmatrix}}_{n x m} \underbrace{\begin{pmatrix} - & v_1^H & - \\ ... & ... & ... \\ - & v_m^H & - \\ \end{pmatrix}}_{m x m}
\end{equation}

If the matrix X is a square matrix of full rank, the matrix decoposition simplifies (so called matrix diagonalization with $U=V$):

\begin{equation}
X = U \Sigma U^H \\
\underbrace{\begin{pmatrix} | & ... & | \\ x_1 & ... & x_m \\ | & ... & | \\ \end{pmatrix}}_{n x n} = \underbrace{\begin{pmatrix} | & ... & | \\ u_1 & ... & u_n \\ | & ... & | \\ \end{pmatrix}}_{n x n} \underbrace{\begin{pmatrix} \sigma_1 & 0 & 0 \\ 0 & ... & 0 \\ 0 & 0 & \sigma_n \\ \end{pmatrix}}_{n x n} \underbrace{\begin{pmatrix} - & u_1^H & - \\ ... & ... & ... \\ - & u_n^H & - \\ \end{pmatrix}}_{n x n}
\end{equation}

In [3]:
import numpy as np

M = np.random.rand(5,5)
#decomposition
U,D,Vh = np.linalg.svd(M)
#test by reversing back
M = np.round( np.matmul(np.matmul(U,np.diag(D)),Vh) ,2)

print("U=\n",np.round(U,2),"\n")
print("D=\n",np.round(D,2),"\n")
print("Vh=\n",np.round(Vh,2),"\n")
print("M=\n",np.round(M,2),"\n")

U=
 [[-0.36  0.66  0.34  0.47 -0.32]
 [-0.39 -0.56 -0.11  0.07 -0.72]
 [-0.55  0.16 -0.75  0.1   0.3 ]
 [-0.52  0.12  0.33 -0.77  0.06]
 [-0.37 -0.46  0.45  0.41  0.53]] 

D=
 [2.58 0.68 0.58 0.11 0.01] 

Vh=
 [[-0.55 -0.41 -0.51 -0.41 -0.32]
 [-0.59  0.17 -0.23  0.43  0.62]
 [-0.25 -0.59  0.7  -0.16  0.29]
 [-0.08  0.51  0.08 -0.78  0.35]
 [ 0.53 -0.45 -0.44 -0.14  0.55]] 

M=
 [[0.19 0.37 0.51 0.5  0.65]
 [0.79 0.39 0.56 0.26 0.07]
 [0.84 0.86 0.4  0.69 0.4 ]
 [0.65 0.41 0.79 0.63 0.51]
 [0.64 0.21 0.74 0.18 0.2 ]] 



### correlation calculation
The correlation of an Matrix is defined as $corr = X^H X$ (correlation of column vectors [data samples]) or alternatively as $corr = X X^H$ (correlation of row vectors [data parameters]). It <br>

\begin{equation}
X^H X = \begin{pmatrix} - & x_1^H & - \\ ... & ... & ... \\ - & x_m^H & - \\ \end{pmatrix} \begin{pmatrix} | & ... & | \\ x_1 & ... & x_m \\ | & ... & | \\ \end{pmatrix} = \begin{pmatrix} x_1^H x_1 & ... & x_1^H x_m \\ ... & ... & ... \\ x_m^H x_1 & ... & x_m^H x_m \\ \end{pmatrix}
\end{equation}

\begin{equation}
X X^H = \begin{pmatrix} | & ... & | \\ x_1 & ... & x_m \\ | & ... & | \\ \end{pmatrix} \begin{pmatrix} - & x_1^H & - \\ ... & ... & ... \\ - & x_m^H & - \\ \end{pmatrix} = \begin{pmatrix} ... & ... & ... \\ ... & ... & ... \\ ... & ... & ... \\ \end{pmatrix}
\end{equation}

This correlation matrices are symmetrical, square, have the same rank as X and have positive eigenvalues.
They can be computed using sigular value decomposition.

\begin{equation}
corr = X^H X = V \Sigma U^H U \Sigma V^H = V \Sigma^2 V^H \\
corr = X X^H = U \Sigma V^H V \Sigma U^H = U \Sigma^2 U^H \\
\end{equation}

This can be reformulated to an eigenvalue problem:<br>

\begin{equation}
corr = X^H X V = V \Sigma^2 \\
corr = X X^H U = U \Sigma^2 \\
\end{equation}

From this follows, that the correlation matricies have the same eigenvalues $\Sigma$.

## approximation with SVD (compression)

By the singular value decomposition we can approximate matrix X by the greatest $\sigma_i$ elements: 

\begin{equation}
X \approx \tilde{X} = \sigma_1 u_1 v_1^H + \sigma_2 u_2 v_2^H + ... \\
= \sigma_1 \begin{pmatrix} | \\ u_1 \\ | \\ \end{pmatrix} \begin{pmatrix} - & v_1^H & - \\ \end{pmatrix} + \sigma_2 \begin{pmatrix} | \\ u_2 \\ | \\ \end{pmatrix} \begin{pmatrix} - & v_2^H & - \\ \end{pmatrix} + ...
\end{equation}

According to the Eckard-Young Teorem this approximation has the smallest frobenius norm ($l_2$) compared to all possible approximations: $argmin_{\tilde{X}} \Big( \sum_{i,j} |x_{ij}-\tilde{x}_{ij}|_2 \Big)$

### solve linear system of equations with SVD
<b>can be used for regression</b><br>

A linear System of equations $Ax = b$ can only be solved unambiguously, if the matrix A is a square matrix of full rank. Otherwise there will be infetly many or no exact solutions. <br>
We can decompose matrix A into $A = U \Sigma V^H$. By subtituion we get $U \Sigma V^H x = b$, wich can be rewritten to $x = V \Sigma^{-1} U^H b$. $A^+ = V \Sigma^{-1} U^H$ is called the Moore-Penrose Pseudoinverse. <br>
For a underdetermined linear system (infinitely many solutions) $\tilde{x} = A^+ b$ produces the solution with the smallest $l_2$ norm of x:

\begin{equation}
min_x |\tilde{x}|_2 \quad \text{with} \quad A \tilde{x} = b
\end{equation}

For a overdetermined linear system (no exact solutions) $\tilde{x} = A^+ b$ produces the solution with the smallest $l_2$ error from b:

\begin{equation}
min_x |A\tilde{x}-b|_2
\end{equation}


### Principal componen analysis PCA

PCA is the method to apply SVD to data to transform it into another coordinate system.
The data (apples) is arranged in a matrix, where each row represent a measurement quantaty (size,weight,color) and each column a specific value for each sample.
Before applying SVD each row is normalised to a mean of 0.

The eigenvectors of the covariance matrix are computed to get $\Sigma$ and the eigenvectors are equal to $V$.
The matrix $U^H$ from the SVD isn't calculated, since it's not used for PCA.
The the Data can be approximately represented with a fraction of the biggest eigenvalues wich lie along corresponding eigenvectors. The data is now transformed.