## solve matrix equation with gauss method

solves 2D linear equations:

\begin{align}
\begin{pmatrix} a_{11} & a_{12} & ... \\ a_{21} & a_{22} & ... \\ ... & ... & ... \end{pmatrix} \begin{pmatrix} x_{1} \\ x_{2} \\ ... \end{pmatrix} = \begin{pmatrix} b_{1} \\ b_{2} \\ ... \end{pmatrix}
\end{align}

In [5]:
#linear matrix solver
#aa*x=bb
import numpy as np


#aa = np.array([[2.0, 4.0, 4.0, 3.0], [1.0, 2.0, -1.0, 5.0], [5.0, 4.0, 2.0, 8.0], [7.0, 3.0, 2.0, 1.0]])
#bb = np.array([1.0, 2.0, 4.0, 6.0])

#aa = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
#bb = np.array([1.0, 2.0, 3.0])

aa = np.array([[1,0.67,0.33],[0.45,1,0.55],[0.67,0.33,1]])
bb = np.array([2,2,2])

dimensions = np.shape(aa)
print('(lines,columns) of matrix aa',dimensions)

print('--------------------------------------------------')
##################################################test dimensions (for quadratic matrix, same vector bb dimension)
if dimensions[0] != dimensions[1] or dimensions[0] != len(bb):
    raise TypeError('matrix not quadratic')
else:
    pass

##################################################modify vektor bb --> cc

'''cc = []
for kk in range(0,len(bb)):
    cc.append([bb[kk]])'''

cc = np.reshape(bb,(3,1))

print('aa:\n',aa)
print('bb:\n',bb)
print('cc = reshaped bb:\n',cc)

print('--------------------------------------------------')
##################################################add vektor cc to matrix cc
aa = np.append(aa, cc,1)

print('combined mattrix aa+cc \n',aa)

print('--------------------------------------------------')
##################################################triangle matrix
pos = 0; counter = 0
while pos < dimensions[1]:
    line = pos + 1
    while line < dimensions[0]:
        if aa[pos][pos] != 0:
            aa[line] = aa[line] - (aa[line][pos]/aa[pos][pos]) * aa[pos]
        elif line == dimensions[0] or counter == dimensions[1] - pos:
            pass
        else:
            #rotate matrix
            cache = np.array(aa[pos])
            iterate = pos
            while iterate < dimensions[0]-1:
                aa[iterate] = np.array(aa[iterate+1])
                iterate += 1
            aa[dimensions[0]-1] = cache
            counter += 1
            line = line - 1
        counter = 0
        line += 1
    pos += 1

print('triangle matrix:')
print(aa)


print('--------------------------------------------------')
##################################################test for zero lines

k=0
while k < dimensions[1]:
    kk = 0
    while kk < dimensions[0]:
        if aa[k][kk] != 0:
            kk=dimensions[0]
        elif kk != dimensions[0]-1:
            kk += 1
        else:
            raise ValueError('matrix linear dependent')
    k += 1

##################################################diagonal matrix
pos = dimensions[1] -1
while pos >= 0:
    line = pos -1
    while line >= 0:
        aa[line] = aa[line] - (aa[line][pos]/aa[pos][pos]) * aa[pos]
        line -= 1
    pos -= 1

print('diagonal mattrix:')
print(aa)

print('--------------------------------------------------')
##################################################unit matrix
for ii in range(0,dimensions[0]):
    aa[ii] = aa[ii]/aa[ii][ii]

print('unit matrix:')
print(aa)

print('--------------------------------------------------')
##################################################resulting values
xx = np.zeros((dimensions[1],), dtype=float)
for jj in range(0,dimensions[0]):
    xx[jj] = aa[jj][dimensions[1]]

print('result:')
print(xx)


(lines,columns) of matrix aa (3, 3)
--------------------------------------------------
aa:
 [[1.   0.67 0.33]
 [0.45 1.   0.55]
 [0.67 0.33 1.  ]]
bb:
 [2 2 2]
cc = reshaped bb:
 [[2]
 [2]
 [2]]
--------------------------------------------------
combined mattrix aa+cc 
 [[1.   0.67 0.33 2.  ]
 [0.45 1.   0.55 2.  ]
 [0.67 0.33 1.   2.  ]]
--------------------------------------------------
triangle matrix:
[[1.         0.67       0.33       2.        ]
 [0.         0.6985     0.4015     1.1       ]
 [0.         0.         0.84724409 0.84724409]]
--------------------------------------------------
diagonal mattrix:
[[1.         0.         0.         1.        ]
 [0.         0.6985     0.         0.6985    ]
 [0.         0.         0.84724409 0.84724409]]
--------------------------------------------------
unit matrix:
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]
--------------------------------------------------
result:
[1. 1. 1.]


In [6]:
#test with numpy solver
import numpy as np

#aa = np.array([[2.0, 4.0, 4.0, 3.0], [1.0, 2.0, -1.0, 5.0], [5.0, 4.0, 2.0, 8.0], [7.0, 3.0, 2.0, 1.0]])
#bb = np.array([1.0, 2.0, 4.0, 6.0])

#aa = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
#bb = np.array([1.0, 2.0, 3.0])

aa = np.array([[1,0.67,0.33],[0.45,1,0.55],[0.67,0.33,1]])
bb = np.array([2,2,2])

np.linalg.solve(aa,bb)

array([1., 1., 1.])